
spring.application.name=eventManagement
spring.datasource.url=jdbc:mysql://localhost:3306/eventManagement
spring.datasource.username=root
spring.datasource.password=@rohan001010

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=singhrohan60870@gmail.com
spring.mail.password=livqghfpohacijoq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
